### ISSUE TITLE
Tax Calculator was swapped to next side when we click to the tax calculator button. I will not be good for the user experience.

### ISSUE THREAD

**Issue by shirshakranabhat** [prajwolsedhainp03/tax-calculation#1]
![gg](https://user-images.githubusercontent.com/103439896/168029961-b80a8857-94fe-484e-8e40-74cc38e36c25.PNG)

**Comment by bizilprajapati123** [comment]
thanks for pointing it out, I completely missed that. let me fix that

**Comment by bizilprajapati123** [comment]
![image](https://user-images.githubusercontent.com/103416443/168215990-c558d306-0ac2-458c-87da-95960c4d8e14.png)

**Comment by bizilprajapati123** [comment]
I have fixed the bug and moved the tax calculator tab in the far right in all pages
