### ISSUE TITLE
The tax rate is incorrect. 10% is not the tax rate allowed for monthly salary of 12000.

### ISSUE THREAD

**Issue by shirshakranabhat** [prajwolsedhainp03/tax-calculation#2]
![gg1](https://user-images.githubusercontent.com/103439896/168029830-98d75723-ef61-469c-9eac-387ec1b27322.PNG)

**Comment by prajwolsedhainp03** [comment]
Oh that looks like something is up with the code. Let me fix it asap

**Comment by prajwolsedhainp03** [comment]
Thank you @shirshakranabhat for finding this. It was a mistake for the tax rate should be 1%
This issue has been fixed.

**Comment by prajwolsedhainp03** [comment]
![image](https://user-images.githubusercontent.com/103408376/168240483-86aa97ef-9e77-4b64-8491-1dfba5a7cbb6.png)
