### ISSUE TITLE
Fix the bug Reset button not working

### ISSUE THREAD

**Issue by shirshakranabhat** [prajwolsedhainp03/tax-calculation#3]
![280105416_430471718890411_2070585518233276637_n](https://user-images.githubusercontent.com/103439896/168031963-c5ab4abf-cf67-4f73-855f-f0d7352934d7.png)

**Comment by bizilprajapati123** [comment]
thanks for the feedback, Let me resolve this asap

**Comment by bizilprajapati123** [comment]
![280242689_416277076989078_558697236171505282_n](https://user-images.githubusercontent.com/103416443/168218659-f88c94ae-4237-4329-9c5c-bf5d6fd9d020.jpg)

**Comment by bizilprajapati123** [comment]
I have fixed the bug by creating a different reset value class, the error should be fixed now. 
thanks

**Comment by prajwolsedhainp03** [comment]
I have fixed the bug by creating a different reset value class.
![image](https://user-images.githubusercontent.com/103408376/177027485-80381732-68fb-41a7-bcdd-10d4187595ee.png)
