### ISSUE TITLE
Color of navbar fixing

### ISSUE THREAD

**Issue by prajwolsedhainp03** [prajwolsedhainp03/tax-calculation#5]
The color of our our nav-bar didn't match the product backlog requirement of the navigation color. So, I assign this issue to the developer to be fixed on time because of the client requirement

**Comment by shirshakranabhat** [comment]
thank you for your feedback i had fixed the problem accoding to the requirement.
![12](https://user-images.githubusercontent.com/103439896/229366539-6e1c5a89-357e-451d-ae22-e6fff03ee3ac.jpg)
