### ISSUE TITLE
Add Search Button #2

### ISSUE THREAD

**Issue by prajwolsedhainp03** [prajwolsedhainp03/tax-calculation#6]
the client suggested to add search button on the nav bar so, the developer are assigned to add search button.

**Comment by shirshakranabhat** [comment]
Noted. I have attached the search box on the nav bar please have a look.
![issue 2](https://user-images.githubusercontent.com/103439896/229367256-9efc4194-ae16-468c-9c95-98fcd9010fcc.jpg)
